### ISSUE TITLE
Effektivisera koden

### ISSUE THREAD

**Issue by perenstrom** [11-X4-UU/Our-first-repository#3]
tjo.pl ser verkligen inte bra ut. Kod överallt, det är omöjligt för en utomstående att sätta sig in i programmet. Fixa, NUUUUU!

**Comment by simfor** [comment]
Du behöver inte bli så arg

**Comment by perenstrom** [comment]
Jag stör mig på att den här issuen är öppen. Jag stänger den nu. :P

**Comment by simfor** [comment]
Bra gjort! Man måste samla mod i några år inför ett sånt här stort beslut ;)
